### ISSUE TITLE
Add another user identifier property

### ISSUE THREAD

**Issue by salagula** [Yvand/LDAPCP#120]
I would like to add another (additional) LDAP class to users:

![grafik](https://user-images.githubusercontent.com/65948353/83887765-2f864000-a749-11ea-94d1-4b442c73692f.png)

How can I add it (in my case myperson) to have finally 'user' and 'myperson' in parallel active? If I do it with PS1 or UI I simply get: .../emailaddress already exists in the collection

![grafik](https://user-images.githubusercontent.com/65948353/83888036-94419a80-a749-11ea-8766-9c283f8f9dbb.png)

**Comment by Yvand** [comment]
The object you are adding is not a LDAP class, it's a new claim type mapping, which is basically a row that you can visualize in the table in central admin > security > LDAPCP claims mapping page.

The error is thrown because claim type emailaddress is already present in that list

**Comment by salagula** [comment]
> The object you are adding is not a LDAP class, it's a new claim type mapping, which is basically a row that you can visualize in the table in central admin > security > LDAPCP claims mapping page.

hmm, are you sure? It is a custom LDAP server and if I change the class to "myperson" I get results:

![grafik](https://user-images.githubusercontent.com/65948353/84054516-ce15d980-a9b3-11ea-916d-54761a277e83.png)

but if I change it to * (wildcard) I get no results anymore

![grafik](https://user-images.githubusercontent.com/65948353/84054873-4c727b80-a9b4-11ea-81c3-61069e711b60.png)

Issue is solved once I get values back with the 'user' & 'myperson' class ...

**Comment by Yvand** [comment]
The object in the PowerShell screenshot was a claim type mapping, but the screenshot of the LDAP class was really the LDAP class, hence the confusion.
Anyway, great that you fixed your issue!

**Comment by salagula** [comment]
no - sorry ... the issue is not solved :-)
I wanted to says:

The issue is solved once I get values back with the 'user' & 'myperson' class ...

**Comment by salagula** [comment]
As said: I have 3 LDAP repos where the ˋuser ´ class is used, now we want to add the fourth one and (unfortunately) this one is not using the user class at all - a custom one is used and this is called ´mypersonˋ. Good would be to get results from both classes, means user and myperson at the same time (upfront I have tested with the single classes and get results from all wished LDAPs). A star (*) as class name did not work work ...

**Comment by Yvand** [comment]
I understand now. Unfortunately, you cannot do this, the LDAP class of a given LDAP property is global to all LDAP connections

**Comment by salagula** [comment]
okay, I tried to configure now:

![image](https://user-images.githubusercontent.com/65948353/84917517-b9c29280-b0bf-11ea-88f4-68af2ea53109.png)

... if I look into my ULs logs and the corresponding LDAP query this looks fine - BUT: from the 23 results 4 are removed (and mine is in the 4):

![image](https://user-images.githubusercontent.com/65948353/84917699-f3939900-b0bf-11ea-94f8-523528c2a174.png)

How does that "create after filtering" work? I thought the 23 results are displayed already based on filters !?

**Comment by Yvand** [comment]
@salagula all the filtering of accounts is done in method [LDAPCP.ProcessLdapResults()](https://github.com/Yvand/LDAPCP/blob/b598963da8b7652193e3c2905b5d0da3cdcdf246/LDAPCP/LDAPCP.cs#L720), and there are many reasons why a result may be removed.
In your case, I think it is because of [this test,](https://github.com/Yvand/LDAPCP/blob/b598963da8b7652193e3c2905b5d0da3cdcdf246/LDAPCP/LDAPCP.cs#L767), but it's hard to say for sure

**Comment by salagula** [comment]
okay, many thanks. My understanding would be: it can be solved if the LDAP filter is extended to include an "OR". Am I right? Maybe it is also interesting for other folks. ...
e.g. (|(objectclass=user)(objectclass=myperson)). Any plan to add such a extention to support more than one class?

**Comment by Yvand** [comment]
@salagula it's not that simple because by design, LDAPCP sends the same query to all LDAP servers.
To support your scenario, it will be necessary to change this design to have a different query for each LDAP server. Honestly, I think it's a huge work for a very rare scenario, and it would also add complexity to the overall design that would make it more difficult to maintain.
With that said, one possible option is that you fork the project and implement this change in your own custom version of LDAPCP
