### ISSUE TITLE
LDAPCP Second Edition - MaxSearchResultsCount.

### ISSUE THREAD

**Issue by sgaukerud** [Yvand/LDAPCP#209]
Hi, @Yvand ,

In LDAPCP Classic we had the ability to adjust the MaxSearchResultsCount.
After upgrading to LDAPCP Second Edition, we do not find this option.
Is it possible to change the value in this version, or is it possible to sort the search result?

The challenge and the reason why we need this:
Our mapping for groups is set up to search on fullName, with Description as the display name.

fullName of the groups has name-format DEP, DEP-SEK1, DEP-SEK2 etc,
where the group DEP is the top-level-group and involves all users.

When we search for e.g. "DEP" in peoplepicker we do not find the group named only "DEP".
To solve this in LDAPCP Classic we set MaxSearchResultsCount=150, which means in practice we get result of all groups if we search for "DEP".

**Comment by Yvand** [comment]
Hi @sgaukerud, indeed, I did not include this property in LDAPCP SE, because I did not think it was useful, and also because it overrides the max count that SharePoint sets, when it calls claims providers, and I did not feel legit to ignore the nax count from SharePoint and dictate my own.

But I hear your scenario, I will do some tests on this and come back to you.
Are you using SharePoint Subscription with modern sites?

**Comment by Yvand** [comment]
@sgaukerud I merged a PR today that re-adds the property `MaxSearchResultsCount`, it will be available in the next version.
Its default value is -1 (which means it is ignored).
To change its value:

```powershell
Add-Type -AssemblyName "Yvand.LDAPCPSE, Version=1.0.0.0, Culture=neutral, PublicKeyToken=80be731bc1a1a740"
$config = [Yvand.LdapClaimsProvider.LDAPCPSE]::GetConfiguration()
$settings = $config.Settings
$settings.MaxSearchResultsCount = 50
$config.ApplySettings($settings, $true)
```
