### ISSUE TITLE
Sharepoint 2013 Implications of Claims Mode Authentication on service applications / Managed Metadata Service

### ISSUE THREAD

**Issue by MiikkaLehtonen** [Yvand/LDAPCP#25]
Hi there, We have an issue when converting Managed Metadata Service Application Windows claims authentication to SAML-based authentication. We are executing script Convert-ManagedMetadataServiceToTrusted.ps1 from the TechNet page  https://technet.microsoft.com/en-us/library/dn745644.aspx.

It throws the following error:

Write-LogError : ERROR: Exception in ShouldExecute: Exception calling ".ctor" with "1" argument(s): "Exception of type 'System.ArgumentException' was thrown.
 Parameter name: configuration"
 At D:\install\Convert-ManagedMetadataServiceToTrusted.ps1:187 char:9
 +         Write-LogError ("Exception in ShouldExecute: {0}" -f $_.Exception.Messag ...
 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-LogError

Write-LogError : ERROR: Stack trace: at Create-Migrator, D:\install\Convert-ManagedMetadataServiceToTrusted.ps1: line 360
 at ShouldExecute, D:\install\Convert-ManagedMetadataServiceToTrusted.ps1: line 169
 at <ScriptBlock>, D:\install\Convert-ManagedMetadataServiceToTrusted.ps1: line 694
 at <ScriptBlock>, D:\install\Convert-ManagedMetadataServiceToTrusted.ps1: line 691
 at <ScriptBlock>, <No file>: line 1
 At D:\install\Convert-ManagedMetadataServiceToTrusted.ps1:188 char:9
 +         Write-LogError ("Stack trace: {0}" -f $_.ScriptStackTrace)
 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-LogError

And the corresponding ULS entry is:

10.27.2017 17:45:36.18 PowerShell.exe (0x5E80) 0x28CC SharePoint Foundation Claims Authentication amcpj Unexpected Trusted login provider has claim provider that isn't SPTrustedBackedByActiveDirectoryClaimProvider. TrustedLoginProvider: 'MESSI'. 2f19f817-4331-0000-f16e-482f3143d301

We are using your great product LDAPCP and earlier we associated to an SPTrustedIdentityTokenIssuer to work:
$trust = Get-SPTrustedIdentityTokenIssuer "MESSI"
$trust.ClaimProviderName = "LDAPCP"
$trust.Update()

Any help would be appreciated.

Thanks,
Miikka

**Comment by Yvand** [comment]
Hi @MiikkaLehtonen, 
As the log mentioned, SharePoint expects to use claims provider SPTrustedBackedByActiveDirectoryClaimProvider but since it's LDAPCP, it stops.

SPTrustedBackedByActiveDirectoryClaimProvider is a quite special, hidden claims provider that was implemented to ease migration from Windows claims to trusted authN.
It is never visible or used explicitely, the only way to use it is to create the SPTrustedIdentityTokenIssuer object using the "-UseDefaultConfiguration" switch, as documented in [kb3042604](https://support.microsoft.com/en-us/help/3042604/the-convert-spwebapplication-command-cannot-convert-from-windows-claim).

So the short answer for you would be to delete the SPTrustedIdentityTokenIssuer and recreate it with the "-UseDefaultConfiguration" switch.
This will "disconnect" LDAPCP from the trust and link SPTrustedBackedByActiveDirectoryClaimProvider to it instead.

Unfortunately, due to the implementation of SPTrustedBackedByActiveDirectoryClaimProvider, it's very likely not going to work in your scenario: 
the problem is the value used to set the entity key of each entity (aka user):
SPTrustedBackedByActiveDirectoryClaimProvider uses specifically the SID of users (remember it's used to migrate winclaims to trusted authN), but:
- I suspect SharePoint doesn't even get the SID of users in your scenario.
- LDAPCP uses the identity claim type for the entity key.

This difference means that if you switch to SPTrustedBackedByActiveDirectoryClaimProvider, you will create mess up your trusted users permissions.

So, I don't know how to resolve your issue, but I would search for a way that doesn't involve using SPTrustedBackedByActiveDirectoryClaimProvider, if possible.

**Comment by MiikkaLehtonen** [comment]
Thanks. I finally decided to change users manually in the managed metadata service. Then I also had to add the Claims based All Authenticated users group to hidden Taxonomy list. The hidden Taxonomy list can be browsed by putting this on the end of your Site Collection URL /Lists/TaxonomyHiddenList/. 

Miikka

**Comment by Yvand** [comment]
Ok, good news that you could do it this way
