### ISSUE TITLE
don't expect LDAPCP results for a web application

### ISSUE THREAD

**Issue by lancegosby** [Yvand/LDAPCP#26]
I'm sorry if this is something simple I have overlooked.

We've been using LDAPCP for a few years with 2 web applications that use ADFS in non-default zones. The people picker has been working perfectly. Recently, we've added a new web application that uses only windows authentication in the default zone. It has only the 1 zone. 

From this new web app, when I use the people picker, I see results from AD as well as LDAPCP. The web app definitely does not have the ADFS Identity Provider enabled. I expected to only see the AD results. I checked an existing web app in the default zone (no ADFS enabled) and I also get LDAPCP results in the people picker.

Is this expected? Is there something that I might be overlooking? I don't have the latest version of LDAPCP installed. My version was from codeplex back in 2015. 

Hopefully my question makes sense.

**Comment by Yvand** [comment]
- If the SPTrustedLoginProvider is enabled in any zone, it is expected that LDAPCP returns results regardless of the current zone where people picker is used. The short explanation is that this is because of a SharePoint limitation and there is no choice.

- If the SPTrustedLoginProvider is not enabled in any zone, LDAPCP should not return any result. I tried and I cannot reproduce your behavior.
You can try to update to the latest version (actually, you should because it's much better) but I don't remember a specific change that fixes this in particular.
You can also check SharePoint logs and filter on Product/Area "LDAPCP" to try to get more info but I don't think they will be very useful for this particular issue.

**Comment by Yvand** [comment]
Hi @lancegosby, any news on this?

**Comment by lancegosby** [comment]
Hi @Yvand . Sorry for not getting back to you.

I've looked into this more and after updating the WSP to v2017.10 in our test environment, the issue has gone away. Hopefully it works in production too.
