### ISSUE TITLE
Not an issue, just a recommendation - color blindness

### ISSUE THREAD

**Issue by steveareeno** [Yvand/LDAPCP#33]
I am red/green color blind and the claims mapping page in central admin uses red/green colored text to signify if a claim is mapped or not. It would be nice to either have a column stating whether it is mapped or use colors that are more contrasting.

Thanks.

**Comment by Yvand** [comment]
Hello, thank you for your suggestion, what colours would you suggest to use instead?
I'm reluctant to add a new column because IMO there are already too many for a good readability...

**Comment by steveareeno** [comment]
I can see what you mean by adding a column. I did a little reading online and found the following colors, when used together, cause the biggest problem for color blind people:

Green & Red
Green & Brown
Blue & Purple
Green & Blue
Light Green & Yellow
Blue & Grey
Green & Grey
Green & Black

Not a big issue, I just grabbed someone walking by and asked them which was which :)

Appreciate the quick response and love your solution!

**Comment by Yvand** [comment]
Thank you for your feedback, I'll keep this in mind and see how I can change the colors for the next version.
What is not clear is if I should completely avoid green (for example), or just avoid mixing green with red?I think it's the latter, I'll make some research to find what other colour to use instead of red.
