### ISSUE TITLE
People picker search in contacts instead of users

### ISSUE THREAD

**Issue by sammtrend** [Yvand/LDAPCP#4]
Hello,

I'm in a case where I would like to read an Active directory where the users are actually contacts and not users. How can I search on contacts in the directory instead of users?
Can you help me?
Any plan to make an option for this (search also in contacts and not only users) in your application?
This is because in the context of ADFS we use FIM to replicate users from a federated company and re-create them into our directory as contacts for security reasons. So we would do the people picker in our directory instead of the initial directory also for security reasons.
THanks

**Comment by Yvand** [comment]
Technically, the reason why LDAPCP doesn't query contacts is because LDAP object class of users is set to "user".
To include contacts, you can try to change it to "person", which includes both users and contacts (at least in Active Directory).
But I never tested this, I don't know if this would work fine.
You can make this change in central administration > security > LDAPCP claims mapping.
Can you give it a try?

**Comment by sammtrend** [comment]
hello, 
Yes it works !!! Thank you very much for your answer ! You saved me a lot of time!

**Comment by Yvand** [comment]
My pleasure!
