### ISSUE TITLE
Assigning SharePoint permission using other attributes with LDAPCP

### ISSUE THREAD

**Issue by Albino1006** [Yvand/LDAPCP#52]
Hello @Yvand ,

We need your suggestion on below:

**Scenario:**
We have some SharePoint sites that are accessible to all in the organization as well as accessible to external users via default group 'Everyone'

**Requirement:**
Now there are some sites that shouldn't be accessible to external users, but should be accessible to members within the organizations. For this case the default group of Everyone doesn't help.

We know permission in SharePoint can be assigned via userID, Security AD group or default group like Everyone.

We would like to know if it it possible to assign permission on SharePoint based on “OUs”, “AD attribute” or “Wildcards” using **LDAPCP**.

**Examples:**
1.	Assign permissions to all users of a particular OU. If there are different OUs for employees and external users.
2.	Allow access to all users who have AD attribute “employeeType=Employee”
3.	Allow access to all users who have userid starting with “X-****”

Awaiting your reply. Thanks.

**Comment by Yvand** [comment]
Hi @Albino1006, unfortunately, due to a design limitation in SharePoint, it's not possible to apply a different filter per site collection:
During the permission creation process, SharePoint passes the URL of the web application (to LDAPCP), instead of the URL of the current site collection.
This behavior affects all custom claims providers.
