### ISSUE TITLE
LDAPCP missing Claim entity type column 

### ISSUE THREAD

**Issue by fvibas** [Yvand/LDAPCP#95]
![image](https://user-images.githubusercontent.com/29219809/63825862-f08fb680-c98e-11e9-8943-bdbb4fd63a0f.png)

I am using LDAP version 12.0.2.20190321.770 and noticed that the Claim entity type column is missing and therefor I couldn't set Formsrole to the Group. I tried updating to the latest version but still I'm not seeing the missing column.

Hope to get some help on this issue as it is affecting the use of AD groups in SharePoint.

**Comment by fvibas** [comment]
Additional info. I have also removed the claim value prefix {fqdn}\ for the Groups but still the AD group permission isn't working

**Comment by Yvand** [comment]
@fvibas column "Claim entity type" was removed because it was causing confusion with the "Entity Type".
Now LDAPCP sets it automatically like this:
- if column "Entity Type" is User: "Claim entity type" is User
- if column "Entity Type" is Group: "Claim entity type" is FormsRole

I don't think this plays a role in your issue. Can you check SharePoint logs and filter on Product/Area "LDAPCP" to see what is happening?

**Comment by fvibas** [comment]
@Yvand. thanks for the Info. I've filtered the ULS for augmentation and the outcome is below.
![image](https://user-images.githubusercontent.com/29219809/64092565-e3583a80-cd87-11e9-8fee-9610ebedd347.png)

But when I do a permission check of the user the membership to the AD group is not shown even though I've added the AD group in SharePoint

**Comment by fvibas** [comment]
@Yvand 

Thanks, will try that out and update you again.

**Comment by Yvand** [comment]
@fvibas any update?
